#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include "headers/core.h"
#include "headers/define.h"
#include "headers/error.h"
#include "headers/object.h"
#include "headers/general.h"
#include "headers/calculate.h"